# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercrypt < Formula
  desc "A tool to generate paper backups of your passwords and other secrets."
  homepage "https://github.com/TMUniversal/papercrypt"
  version "1.2.7"
  license "AGPL-3.0-or-later"

  on_macos do
    on_intel do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.7/papercrypt_Darwin_x86_64.tar.gz"
      sha256 "bb4f87a8d02e5489ae6ca54a38da6f3933ecec7605ebbe9437f1438b9449a3d5"

      def install
        bin.install "papercrypt"
        bash_completion.install "completions/papercrypt.bash" => "papercrypt"
        fish_completion.install "completions/papercrypt.fish"
        zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
        man1.install "manpages/papercrypt.1.gz"
      end
    end
    on_arm do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.7/papercrypt_Darwin_arm64.tar.gz"
      sha256 "42a2d05d3d101f43525c59b41c0bf1a8809193703381563fee36c4974f332d2f"

      def install
        bin.install "papercrypt"
        bash_completion.install "completions/papercrypt.bash" => "papercrypt"
        fish_completion.install "completions/papercrypt.fish"
        zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
        man1.install "manpages/papercrypt.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.7/papercrypt_Linux_x86_64.tar.gz"
        sha256 "b319d4bbe793d06eaf1748a99442c15cb9e03df987a328e287e00b2e171375d5"

        def install
          bin.install "papercrypt"
          bash_completion.install "completions/papercrypt.bash" => "papercrypt"
          fish_completion.install "completions/papercrypt.fish"
          zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
          man1.install "manpages/papercrypt.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.7/papercrypt_Linux_arm64.tar.gz"
        sha256 "8bce8b64779fc01362f276af38f4eb0da4e3209627d84fa6996924c416ca55c6"

        def install
          bin.install "papercrypt"
          bash_completion.install "completions/papercrypt.bash" => "papercrypt"
          fish_completion.install "completions/papercrypt.fish"
          zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
          man1.install "manpages/papercrypt.1.gz"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        papercrypt help
    EOS
  end

  test do
    system "#{bin}/papercrypt version"
  end
end
