# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercrypt < Formula
  desc "A tool to generate paper backups of your passwords and other secrets."
  homepage "https://github.com/TMUniversal/papercrypt"
  version "1.2.2"
  license "AGPL-3.0-or-later"

  on_macos do
    on_intel do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.2/papercrypt_Darwin_x86_64.tar.gz"
      sha256 "ce3814bce1664d858961b928499fab54bc1a3311ccbf292ae47127d6f99520d8"

      def install
        bin.install "papercrypt"
        bash_completion.install "completions/papercrypt.bash" => "papercrypt"
        fish_completion.install "completions/papercrypt.fish"
        zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
        man1.install "manpages/papercrypt.1.gz"
      end
    end
    on_arm do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.2/papercrypt_Darwin_arm64.tar.gz"
      sha256 "6937424eca9f0c08bd6e59c3007e7d050e8f7d30b1e492790055b9cc8b8cebc6"

      def install
        bin.install "papercrypt"
        bash_completion.install "completions/papercrypt.bash" => "papercrypt"
        fish_completion.install "completions/papercrypt.fish"
        zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
        man1.install "manpages/papercrypt.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.2/papercrypt_Linux_x86_64.tar.gz"
        sha256 "eea39b3a5ba9bdf2124627d937a9cb23eabd42c0ff8a1d292e7d27213d823ab7"

        def install
          bin.install "papercrypt"
          bash_completion.install "completions/papercrypt.bash" => "papercrypt"
          fish_completion.install "completions/papercrypt.fish"
          zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
          man1.install "manpages/papercrypt.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmuniversal/papercrypt/releases/download/v1.2.2/papercrypt_Linux_arm64.tar.gz"
        sha256 "1d3cde30fc292df1ad5b95069acda93ae3caa0f2944d8947233083fef804f356"

        def install
          bin.install "papercrypt"
          bash_completion.install "completions/papercrypt.bash" => "papercrypt"
          fish_completion.install "completions/papercrypt.fish"
          zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
          man1.install "manpages/papercrypt.1.gz"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        papercrypt help
    EOS
  end

  test do
    system "#{bin}/papercrypt version"
  end
end
