# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Papercrypt < Formula
  desc "A tool to generate paper backups of your passwords and other secrets."
  homepage "https://github.com/TMUniversal/papercrypt"
  version "2.0.1"
  license "AGPL-3.0-or-later"

  on_macos do
    on_intel do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v2.0.1/papercrypt_Darwin_x86_64.tar.gz"
      sha256 "1129b282b4e5914b0e4c8e70e161801371d4f784967ce866270b4183d41acbff"

      def install
        bin.install "papercrypt"
        bash_completion.install "completions/papercrypt.bash" => "papercrypt"
        fish_completion.install "completions/papercrypt.fish"
        zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
        man1.install "manpages/papercrypt.1.gz"
      end
    end
    on_arm do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v2.0.1/papercrypt_Darwin_arm64.tar.gz"
      sha256 "ac4cd1dc820b2679edec1767da195f45b5d3294e5646cc7a5215854c20936db6"

      def install
        bin.install "papercrypt"
        bash_completion.install "completions/papercrypt.bash" => "papercrypt"
        fish_completion.install "completions/papercrypt.fish"
        zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
        man1.install "manpages/papercrypt.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmuniversal/papercrypt/releases/download/v2.0.1/papercrypt_Linux_x86_64.tar.gz"
        sha256 "09f5a889b545b658e23897b250f44d13161505fd8d1b24042fab89fc4b4f0c02"

        def install
          bin.install "papercrypt"
          bash_completion.install "completions/papercrypt.bash" => "papercrypt"
          fish_completion.install "completions/papercrypt.fish"
          zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
          man1.install "manpages/papercrypt.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/tmuniversal/papercrypt/releases/download/v2.0.1/papercrypt_Linux_arm64.tar.gz"
        sha256 "85766c6db46323696fd5a4ad45c3ccc1db23715639c841fb6ca0b9fe1f1de1dd"

        def install
          bin.install "papercrypt"
          bash_completion.install "completions/papercrypt.bash" => "papercrypt"
          fish_completion.install "completions/papercrypt.fish"
          zsh_completion.install "completions/papercrypt.zsh" => "_papercrypt"
          man1.install "manpages/papercrypt.1.gz"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To get started, run:
        papercrypt help
    EOS
  end

  test do
    system "#{bin}/papercrypt version"
  end
end
