# This file was generated by GoReleaser. DO NOT EDIT.
cask "papercrypt" do
  version "3.3.0"

  on_macos do
    on_arm do
      sha256 "90d3718f42c8679f3433fcf43d2f9c265a8d105b7ce4dfb0512876cf181a70d9"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "21c8689420ac909430a1963b20ffb6993a9f01bfbe1a870c5c8858e241389b0d"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "25e88447fce033942a8237edbddb9ed552036d3c7309bf6397be2722c0069c37"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "47a0728c6ecc6d87b104768a9fa2b3151b913f13a7be1525686acd00ce556e69"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Linux_x86_64.tar.gz"
    end
  end

  name "papercrypt"
  desc "A tool to generate paper backups of your passwords and other secrets."
  homepage "https://github.com/TMUniversal/papercrypt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "papercrypt"
  manpage "manpages/papercrypt.1.gz"
  bash_completion "completions/papercrypt.bash"
  fish_completion "completions/papercrypt.fish"
  zsh_completion "completions/papercrypt.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/papercrypt"]
    end

    system_command "#{staged_path}/papercrypt", args: ["version"]
  end

  # No zap stanza required

  caveats <<~EOS
    To get started, run:
      papercrypt help
  EOS
end
