# This file was generated by GoReleaser. DO NOT EDIT.
cask "papercrypt" do
  name "papercrypt"
  desc "A tool to generate paper backups of your passwords and other secrets."
  homepage "https://github.com/TMUniversal/papercrypt"
  version "2.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "papercrypt"
  manpage "manpages/papercrypt.1.gz"
  bash_completion "completions/papercrypt.bash"
  zsh_completion "completions/papercrypt.zsh"
  fish_completion "completions/papercrypt.fish"

  on_macos do
    on_intel do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Darwin_x86_64.tar.gz"
      sha256 "f7d43e13f0512e9aa92175702912bd97dfcb15df874d6967418c4bf2620ee9c0"
    end
    on_arm do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Darwin_arm64.tar.gz"
      sha256 "6e80222f7fa29c29d654b98d9710e5af5b840441c4904a4b6f3c61b10c21afc4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Linux_x86_64.tar.gz"
      sha256 "c387678c2fe1c5d521b5f1dd2fa051ae04f8b17dd584e6fa1a1523b3eff92a0e"
    end
    on_arm do
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Linux_arm64.tar.gz"
      sha256 "31cf1a2b488fad7fffa4629e8b1476e0d13826b997f1412923122f5bb5965587"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/papercrypt"]
    end

    system_command "#{staged_path}/papercrypt", args: ["version"]
  end

  caveats do
    "To get started, run:"
    "  papercrypt help"
  end

  # No zap stanza required
end
