# This file was generated by GoReleaser. DO NOT EDIT.
cask "papercrypt" do
  version "3.1.1"

  on_macos do
    on_arm do
      sha256 "2a167c4e1053fb3197a2fc45bb16e2733cbe5eb67a75d251d0126e28f7140e78"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "be8dcfde22199d11c79c9c3316f596677bf9df606742fc2eb67640d5baf4bd28"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Darwin_x86_64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b616edd501a05d3ca4608ebee588d49ba50eb773f3158595746e38a08d2622f7"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "30029b862fbcda9eff20429e246263d4b4924992a8229249f92e63b2c30173f2"
      url "https://github.com/tmuniversal/papercrypt/releases/download/v#{version}/papercrypt_Linux_x86_64.tar.gz"
    end
  end

  name "papercrypt"
  desc "A tool to generate paper backups of your passwords and other secrets."
  homepage "https://github.com/TMUniversal/papercrypt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "papercrypt"
  manpage "manpages/papercrypt.1.gz"
  bash_completion "completions/papercrypt.bash"
  fish_completion "completions/papercrypt.fish"
  zsh_completion "completions/papercrypt.zsh"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/papercrypt"]
    end

    system_command "#{staged_path}/papercrypt", args: ["version"]
  end

  # No zap stanza required

  caveats <<~EOS
    To get started, run:
      papercrypt help
  EOS
end
